name: aqueducts
adopt-info: aqueducts-source
base: core22
architectures:
- amd64
confinement: strict
grade: stable
issues: https://github.com/kenvandine/aqueducts-snap/issues
contact: https://endlessstudios.com/
license: Proprietary

apps:
  aqueducts:
    extensions: [gnome]
    command: Aqueducts/Aqueducts.x86_64
    desktop: com.endlessnetwork.aqueducts.desktop
    common-id: com.endlessnetwork.aqueducts.desktop
    plugs:
      - audio-playback
      - joystick
      - network

parts:
  aqueducts:
    source: https://github.com/endless-network/Aqueducts_Binary/releases/download/v1.2.2/Aqueducts.zip
    plugin: dump
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/Aqueducts/Aqueducts.x86_64
  aqueducts-source:
    source: https://github.com/endless-network/Aqueducts_Binary/archive/refs/tags/v1.2.2.tar.gz
    plugin: dump
    parse-info: [com.endlessnetwork.aqueducts.appdata.xml]
    override-pull: |
      craftctl default
      sed -i 's|Icon=com.endlessnetwork.aqueducts$|Icon=${SNAP}/meta/gui/icon.png|g' $CRAFT_PART_SRC/com.endlessnetwork.aqueducts.desktop
      sed -i 's|Exec=com.endlessnetwork.aqueducts.sh$|Exec=aqueducts|g' $CRAFT_PART_SRC/com.endlessnetwork.aqueducts.desktop
      # Work around the latest version number missing from the releases section of appdata
      sed -i 's|version="1.2.1|version="1.2.2|g' $CRAFT_PART_SRC/com.endlessnetwork.aqueducts.appdata.xml

      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp com.endlessnetwork.aqueducts_256.png $CRAFT_PART_INSTALL/meta/gui/icon.png
